### ISSUE TITLE
Links to gene lists no longer work

### ISSUE THREAD

**Issue by wdecoster** [oganm/neuroExpressoAnalysis#9]
Hi,

Great resource. Coming back here after a while I notice the links to the gene lists at http://pavlab.msl.ubc.ca/data-and-supplementary-information/supplement-to-mancarci-et-al-neuroexpresso/ doesn't work anymore, e.g. 
https://github.com/PavlidisLab/neuroExpressoAnalysis/tree/master/analysis/01.SelectGenes/markerGeneTSVs

Cheers,  
Wouter

**Comment by oganm** [comment]
Thank you for notifying. I'll fix the page. For now please refer to https://github.com/PavlidisLab/neuroExpressoAnalysis/blob/master/analysis/01.SelectGenes/README.md
 
@ppavlidis wordpress updates to the page doesn't seem to be going live

**Comment by ppavlidis** [comment]
I'll have it looked into.

**Comment by oganm** [comment]
Links restored

**Comment by wdecoster** [comment]
That was quick, thanks!
